AWSTemplateFormatVersion: "2010-09-09"
Description: "S3 Bucket Management System with Authentication"

Parameters:
  NotificationEmail:
    Type: String
    Description: Email for notifications
    Default: your-email@example.com
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
  AdminEmails:
    Type: CommaDelimitedList
    Description: Comma-separated list of admin email addresses (e.g., admin1@example.com,admin2@example.com)
    Default: ""

Resources:
  # Cognito User Pool
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${Environment}-bucket-management-users"
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
      AutoVerifiedAttributes:
        - email
      MfaConfiguration: "OFF"
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: true
        - Name: name
          AttributeDataType: String
          Required: true
          Mutable: true

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ClientName: !Sub "${Environment}-bucket-management-client"
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      PreventUserExistenceErrors: ENABLED
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days
      AccessTokenValidity: 1
      IdTokenValidity: 1
      RefreshTokenValidity: 30

  CognitoIdentityPool:
    Type: AWS::Cognito::IdentityPool
    DependsOn: CognitoUserPoolClient
    Properties:
      IdentityPoolName: !Sub "${Environment}-bucket-management-identity-pool"
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId: !Ref CognitoUserPoolClient
          ProviderName: !Sub cognito-idp.${AWS::Region}.amazonaws.com/${CognitoUserPool}          

  # DynamoDB Table for metadata
  BucketMetadataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Environment}-bucket-metadata"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: project_name
          AttributeType: S
        - AttributeName: bucket_name
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: project_name
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: bucket-name-index
          KeySchema:
            - AttributeName: bucket_name
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: user-id-index
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # SNS Topic for notifications
  BucketNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${Environment}-bucket-notifications"
      Subscription:
        - Endpoint: !Ref NotificationEmail
          Protocol: email

  # Note: S3 bucket for Lambda code is managed by the deploy script
  # It's created outside of CloudFormation to avoid conflicts
  # Bucket name: ${Environment}-lambda-deployment-packages-${AWS::AccountId}

  # IAM Role for Lambda functions
  BucketManagementRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Environment}-bucket-management-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: BucketManagementPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:CreateBucket
                  - s3:DeleteBucket
                  - s3:GetBucketLocation
                  - s3:ListBucket
                  - s3:ListObjects
                  - s3:ListObjectsV2
                  - s3:DeleteObject
                  - s3:DeleteObjectVersion
                  - s3:PutBucketPublicAccessBlock
                  - s3:PutBucketVersioning
                  - s3:PutBucketEncryption
                  - s3:PutEncryptionConfiguration
                  - s3:HeadBucket
                Resource: "*"
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - !GetAtt BucketMetadataTable.Arn
                  - !Sub "${BucketMetadataTable.Arn}/index/*"
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref BucketNotificationTopic
              - Effect: Allow
                Action:
                  - cognito-idp:AdminListGroupsForUser
                  - cognito-idp:ListUsersInGroup
                Resource: !GetAtt CognitoUserPool.Arn
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub "arn:aws:s3:::${Environment}-lambda-deployment-packages-${AWS::AccountId}/*"

  # Lambda: Create Bucket (Enhanced)
  CreateBucketFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${Environment}-create-bucket"
      Runtime: python3.9
      Handler: index.lambda_handler
      Role: !GetAtt BucketManagementRole.Arn
      Timeout: 30
      MemorySize: 128
      Environment:
        Variables:
          TABLE_NAME: !Ref BucketMetadataTable
          SNS_TOPIC: !Ref BucketNotificationTopic
          ENVIRONMENT: !Ref Environment
          REGION: !Ref AWS::Region
      Code:
        S3Bucket: !Sub "${Environment}-lambda-deployment-packages-${AWS::AccountId}"
        S3Key: !Sub "${Environment}-create-bucket.zip"

  # Lambda: List Buckets (Enhanced)
  ListBucketsFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${Environment}-list-buckets"
      Runtime: python3.9
      Handler: index.lambda_handler
      Role: !GetAtt BucketManagementRole.Arn
      Timeout: 30
      MemorySize: 128
      Environment:
        Variables:
          TABLE_NAME: !Ref BucketMetadataTable
          USER_POOL_ID: !Ref CognitoUserPool
      Code:
        S3Bucket: !Sub "${Environment}-lambda-deployment-packages-${AWS::AccountId}"
        S3Key: !Sub "${Environment}-list-buckets.zip"

  # Cognito Admin Group (Super Admin)
  AdminGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: admins
      UserPoolId: !Ref CognitoUserPool
      Description: Super Administrators with full system access (no auto-heal on delete)
      Precedence: 1

  # Cognito Business Admin Group
  BusinessAdminGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: business-admins
      UserPoolId: !Ref CognitoUserPool
      Description: Business Administrators with access to all buckets and reports (auto-heal on delete)
      Precedence: 2

  # Lambda: Delete Bucket
  DeleteBucketFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${Environment}-delete-bucket"
      Runtime: python3.9
      Handler: index.lambda_handler
      Role: !GetAtt BucketManagementRole.Arn
      Timeout: 30
      MemorySize: 128
      Environment:
        Variables:
          TABLE_NAME: !Ref BucketMetadataTable
          USER_POOL_ID: !Ref CognitoUserPool
          REGION: !Ref AWS::Region
          ADMIN_EMAILS: !Join [',', !Ref AdminEmails]
      Code:
        S3Bucket: !Sub "${Environment}-lambda-deployment-packages-${AWS::AccountId}"
        S3Key: !Sub "${Environment}-delete-bucket.zip"

  # Lambda: Monitor and Heal Buckets (Enhanced)
  MonitorBucketsFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${Environment}-monitor-buckets"
      Runtime: python3.9
      Handler: index.lambda_handler
      Role: !GetAtt BucketManagementRole.Arn
      Timeout: 300
      MemorySize: 256
      Environment:
        Variables:
          TABLE_NAME: !Ref BucketMetadataTable
          SNS_TOPIC: !Ref BucketNotificationTopic
          ENVIRONMENT: !Ref Environment
          REGION: !Ref AWS::Region
      Code:
        S3Bucket: !Sub "${Environment}-lambda-deployment-packages-${AWS::AccountId}"
        S3Key: !Sub "${Environment}-monitor-buckets.zip"

  # API Gateway
  BucketManagementAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub "${Environment}-bucket-management-api"
      Description: API for S3 bucket management
      EndpointConfiguration:
        Types:
          - REGIONAL

  # Cognito Authorizer
  CognitoAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    DependsOn: CognitoUserPool
    Properties:
      Name: CognitoAuthorizer
      Type: COGNITO_USER_POOLS
      IdentitySource: method.request.header.Authorization
      RestApiId: !Ref BucketManagementAPI
      ProviderARNs:
        - !GetAtt CognitoUserPool.Arn

  # CORS Support
  CorsOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref BucketManagementAPI
      ResourceId: !GetAtt BucketManagementAPI.RootResourceId
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  # API Gateway Resources and Methods
  BucketsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref BucketManagementAPI
      ParentId: !GetAtt BucketManagementAPI.RootResourceId
      PathPart: buckets

  BucketsOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref BucketManagementAPI
      ResourceId: !Ref BucketsResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  CreateBucketMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref BucketManagementAPI
      ResourceId: !Ref BucketsResource
      HttpMethod: POST
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref CognitoAuthorizer
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations
          - LambdaArn: !GetAtt CreateBucketFunction.Arn

  ListBucketsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref BucketManagementAPI
      ResourceId: !Ref BucketsResource
      HttpMethod: GET
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref CognitoAuthorizer
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations
          - LambdaArn: !GetAtt ListBucketsFunction.Arn

  DeleteBucketMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref BucketManagementAPI
      ResourceId: !Ref BucketsResource
      HttpMethod: DELETE
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref CognitoAuthorizer
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations
          - LambdaArn: !GetAtt DeleteBucketFunction.Arn

  # Lambda permissions for API Gateway
  CreateBucketPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref CreateBucketFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${BucketManagementAPI}/*/POST/buckets"

  ListBucketsPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ListBucketsFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${BucketManagementAPI}/*/GET/buckets"

  DeleteBucketPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DeleteBucketFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${BucketManagementAPI}/*/DELETE/buckets"

  # API Gateway Deployment
  APIDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - CreateBucketMethod
      - ListBucketsMethod
      - DeleteBucketMethod
      - BucketsOptionsMethod
      - CorsOptionsMethod
    Properties:
      RestApiId: !Ref BucketManagementAPI
      StageName: !Ref Environment

  # EventBridge Rule for monitoring
  MonitoringRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Monitor S3 buckets every 5 minutes"
      ScheduleExpression: "rate(5 minutes)"
      State: ENABLED
      Targets:
        - Arn: !GetAtt MonitorBucketsFunction.Arn
          Id: "MonitorBucketsTarget"

  # EventBridge permission for Lambda
  MonitoringPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref MonitorBucketsFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt MonitoringRule.Arn

  # IAM Role for authenticated Cognito users
  CognitoAuthRole:
    Type: AWS::IAM::Role
    DependsOn: CognitoIdentityPool
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                "cognito-identity.amazonaws.com:aud": !Ref CognitoIdentityPool
              "ForAnyValue:StringLike":
                "cognito-identity.amazonaws.com:amr": authenticated
      Policies:
        - PolicyName: CognitoAuthPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - execute-api:Invoke
                Resource: "*"

  CognitoIdentityPoolRoleAttachment:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    DependsOn: CognitoAuthRole
    Properties:
      IdentityPoolId: !Ref CognitoIdentityPool
      Roles:
        authenticated: !GetAtt CognitoAuthRole.Arn

Outputs:
  APIEndpoint:
    Description: API Gateway endpoint
    Value: !Sub "https://${BucketManagementAPI}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"
    Export:
      Name: !Sub "${Environment}-bucket-api-endpoint"

  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref CognitoUserPool
    Export:
      Name: !Sub "${Environment}-user-pool-id"

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref CognitoUserPoolClient
    Export:
      Name: !Sub "${Environment}-user-pool-client-id"

  IdentityPoolId:
    Description: Cognito Identity Pool ID
    Value: !Ref CognitoIdentityPool
    Export:
      Name: !Sub "${Environment}-identity-pool-id"

  DynamoDBTable:
    Description: DynamoDB table name
    Value: !Ref BucketMetadataTable
    Export:
      Name: !Sub "${Environment}-bucket-metadata-table"

  SNSTopic:
    Description: SNS topic ARN
    Value: !Ref BucketNotificationTopic
    Export:
      Name: !Sub "${Environment}-sns-topic"